server:
  port: 8800
  context-path: /
  session:
    cookie:
      max-age: 14400
      path: /
      domain: .test.com
      secure: true
      http-only: true
    timeout: 28800
  tomcat:
    max-threads: 300

spring:
  http:
    encoding:
      charset: UTF-8
  velocity:
    suffix: .vm
    properties:
      input.encoding: UTF-8
      output.encoding: UTF-8
      eventhandler:
        referenceinsertion:
          class: com.ksy.winning.velocity.MyRefrenceInsertionEventHandler
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://seyun.synology.me:3106/winning?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wndcjs126KSY

logging:
  config: classpath:logback-spring.xml
